### ISSUE TITLE
Conflict with MMM-GoogleTasks ?

### ISSUE THREAD

**Issue by daniel2887** [lavolp3/MMM-AVStock#46] opened 2020-10-31 20:24 UTC
Below is a minimal module config snippet (can be pasted into `config.js.sample`) with this module installed as well as MMM-GoogleTasks. As long as both are enabled, MMM-AVStock doesn't show up at all. Once GoogleTasks is disabled (commented out), AVStock shows up again. Anyone know what's going on? I haven't seen such a conflict yet. Please let me know what other info would be useful to you.

```
        modules: [              
                {               
                        module: "alert",
                },              
                {       
                        module: "updatenotification",
                        position: "top_bar"
                },      
                {       
                        module: "clock",
                        position: "top_left"
                },
                {       
                        module: "MMM-AVStock",
                        position: "lower_third",
                },
                {
                        // Seems to prevent AVStock module from showing up
                        module: "MMM-GoogleTasks",
                        position: "top_right",
                },
        ]       
```

**Comment by lavolp3** [comment] 2020-10-31 20:55
Well how fitting that I wanted to have a look at a Google tasks module fort my mirror next.
I'll check it out.

**Comment by lavolp3** [comment] 2020-11-02 16:10
I was able to reproduce the error and fix it by fixing an error in the MMM-GoogleTasks module that surfaced in my developers console.
Then it worked.
The line creating the error is in MMM-GoogleTasks.js
```
var numTasks = Object.keys(this.tasks).length;
```

I will fork the module and send a PR later tonight.
Commenting the line out would not work but with a bit of JS knowledge you could place it into a if-else-statement.

**Comment by lavolp3** [comment] 2020-11-02 22:27
Closing the issue here since it is not related to this module.
You can follow further on the MMM-GoogleTasks page, although I'm afraid it is dormant. 
I'm working on a todo list with several options (MicroDs Too, Google, Todoist) so stay tuned.

**Closed as completed by lavolp3** 2020-11-02 22:27 UTC
