### ISSUE TITLE
Ticker Resets after 6 stocks

### ISSUE THREAD

**Issue by alicornea** [lavolp3/MMM-AVStock#75] opened 2024-05-29 11:09 UTC
I have a ticker with 8 stocks but the last two cannot be seen as the position resets to 0.

**Comment by lavolp3** [comment] 2024-06-03 06:52
Hi alicornea! 
I can't reproduce this. 8 stocks work for me. 
Could be a conflict with the width of the module.
Can you send me your config?

**Comment by lavolp3** [comment] 2024-08-07 10:36
@alicornea anything? 
Otherwise I'll close it.

**Comment by alicornea** [comment] 2024-08-07 15:16
it works now, thank you!
    On Wednesday, August 7, 2024 at 01:36:22 PM GMT+3, Dirk ***@***.***> wrote:  
 
 


@alicornea anything?
Otherwise I'll close it.

**Closed as completed** 2024-08-18 08:05 UTC
