### ISSUE TITLE
Suggestion: Font and/or text size change?

### ISSUE THREAD

**Issue by koles0ff** [lavolp3/MMM-AVStock#37] opened 2020-09-11 08:54 UTC
Hello!

Please reply if there is possibility to change the module font? Currently it differs a lot from other modules and Stock table looks huge :) 
For example, here is my setup:  [https://ibb.co/PxhyHTr](https://ibb.co/PxhyHTr)
Would be great to have possibility to make font thinner (maybe disabling **bold** header?) or zoom the whole table to 70-80%.
Additionally, the status line of "last quote" does not change its position depending on the module location. Would be nice to have it on the left for position = left_smth and on the right if position =righ_smth

**Comment by lavolp3** [comment] 2020-09-18 13:11
Is your issue fixed with the latest merges in the meantime?

**Comment by lavolp3** [comment] 2020-09-18 14:22
yes, the module works now with the `classes` config option.
So you can give it a class according tho the MM standard: `xsmall`, `small`, `normal`, `large`, `xlarge`
Have a look in the README.

**Comment by koles0ff** [comment] 2020-09-18 14:31
Ok, got it, thanks. It made font much better, however, this whole module looks still a bit strange: [https://ibb.co/fxZX5jz](https://ibb.co/fxZX5jz)
 - Last update stamp is on the right 
 - Seems that chart stretches columns in the table, despite chart is configured as "narrow"--> chartWidth: 400

**Comment by koles0ff** [comment] 2020-09-21 08:50
I tried this at first place, but this messed up the module completely: [https://ibb.co/h8sHgSb](https://ibb.co/h8sHgSb)

This is my current config:

```
  module: "MMM-AVStock",
  position: "top_left",
  config: {
        apiKey : "apikey",
        symbols : ["EURRUB","USDRUB"],
        showChart: true,
        classes: "xsmall",
        width: 400,
        alias:["EURO","USD"],

        timeFormat: "YYYY-MM-DD HH:mm:ss",
        }
},
```

**Comment by lavolp3** [comment] 2020-09-21 11:07
same error as #41 but I can't reproduce it here...
Tried this just today on my mirror with a fresh install of v2.3.0 and it showed perfectly.
Will have to look further into that.
I have a feeling that the error is due to electron and positioning of elements in a flex grid.
If yes, we have a problem :-)

**Comment by lavolp3** [comment] 2020-09-21 11:09
which MM version do you have installed?
Do you have the latest version? master or develop branch?

**Comment by koles0ff** [comment] 2020-09-21 11:24
Latest one, master branch. Same bug I see with web version, BTW.

**Comment by lavolp3** [comment] 2020-09-21 12:23
What happens if you include 
```
direction: 'column'
```
in your config?

**Comment by koles0ff** [comment] 2020-09-21 12:57
Yeee! We have this awesome result: [https://ibb.co/sJYy8vS](https://ibb.co/sJYy8vS)

**Comment by lavolp3** [comment] 2020-09-21 13:00
Good, keep it that way for now.
With the next update I will set `column` as default.
For now it's difficult for me to see why this does not work.

**Closed as completed by lavolp3** 2020-09-21 13:00 UTC
